### ISSUE TITLE
Failing to download gdk from unity

### ISSUE THREAD

**Issue by marshfellowML** [spatialos/gdk-for-unity#954]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
I followed the instructions and tried both the manual git setup as well as downloading the zip. I'm on Unity 2018.3.11.1f

Everytime I open up the project I get this:

```
Downloading core-dynamic-x86-win32 to C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86-win32.zip...
Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86-win32' and version '13.7.1-gdk-for-unity' to 'C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86-win32.zip'
Downloading core-dynamic-x86_64-win32 to C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-win32.zip...
Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86_64-win32' and version '13.7.1-gdk-for-unity' to 'C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-win32.zip'
Downloading core-dynamic-x86_64-linux to C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-linux.zip...
Successfully retrieved package type 'worker_sdk' with name 'core-dynamic-x86_64-linux' and version '13.7.1-gdk-for-unity' to 'C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-dynamic-x86_64-linux.zip'
Downloading core-bundle-x86_64-macos to C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-bundle-x86_64-macos.zip...
Successfully retrieved package type 'worker_sdk' with name 'core-bundle-x86_64-macos' and version '13.7.1-gdk-for-unity' to 'C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-bundle-x86_64-macos.zip'
Downloading core-static-fullylinked-arm-ios to C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-static-fullylinked-arm-ios.zip...
Downloading...
Encountered an error during command execution.
System.Exception: Exit code 1 while running:
C:\Users\vesha\.improbable\spatial\spatial.exe
	--json_output
	package
	retrieve
	worker_sdk
	core-static-fullylinked-arm-ios
	13.7.1-gdk-for-unity
	"C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity-fps-starter-project\workers\unity\build\CoreSdk\13.7.1-gdk-for-unity\core-static-fullylinked-arm-ios.zip"
   at Improbable.Common.RunRedirected(String command, String[] arguments) in C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Common.cs:line 92
   at Improbable.Program.DownloadPackages(IEnumerable`1 packages, String spatialPath, String coreSdkVersion) in C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Program.cs:line 98
   at Improbable.Program.Main(String[] args) in C:\Users\vesha\Documents\blah\gdk-for-unity-fps-starter-project-0.2.2\gdk-for-unity\workers\unity\Packages\com.improbable.gdk.tools\.DownloadCoreSdk\Program.cs:line 55

UnityEngine.Debug:LogError(Object)
Improbable.Gdk.Tools.RedirectedProcess:Run() (at C:/Users/vesha/Documents/blah/gdk-for-unity-fps-starter-project-0.2.2/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs:156)
Improbable.Gdk.Tools.DownloadCoreSdk:Download() (at C:/Users/vesha/Documents/blah/gdk-for-unity-fps-starter-project-0.2.2/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:133)
Improbable.Gdk.Tools.DownloadCoreSdk:DownloadForceMenu() (at C:/Users/vesha/Documents/blah/gdk-for-unity-fps-starter-project-0.2.2/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:47)

```

Followed by this error

```
Failed to download SpatialOS Core Sdk version 13.7.1-gdk-for-unity. You can use SpatialOS -> Download CoreSDK (force) to retry this.
UnityEngine.Debug:LogError(Object)
Improbable.Gdk.Tools.DownloadCoreSdk:Download() (at C:/Users/vesha/Documents/blah/gdk-for-unity-fps-starter-project-0.2.2/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:139)
Improbable.Gdk.Tools.DownloadCoreSdk:DownloadForceMenu() (at C:/Users/vesha/Documents/blah/gdk-for-unity-fps-starter-project-0.2.2/gdk-for-unity/workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs:47)

```

I try force downloading but it's just the same thing over and over again. I checked my firewall permissions and spatial and unity are both clear. 

Any idea why this is failing?

**Comment by marshfellowML** [comment]
I dug into the logs and found the file that was failing to download. It had a link referenced in the log so i downloaded and renamed it manually and put it in the cache directory is was expecting. Things were fine the next time i reran
